name: Test

on: [pull_request, push]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
    - uses: zendesk/checkout@v2
    - name: Use Node.js
      uses: zendesk/setup-node@v1
      with:
        node-version: '12.x'
    - run: yarn install
    - run: yarn lint
    - run: yarn test
    - run: yarn test:functional
      env:
        CI: true

  build-mac:
    runs-on: macos-10.15
    steps:
    - uses: zendesk/checkout@v2
    - name: Use Node.js
      uses: zendesk/setup-node@v1
      with:
        node-version: '12.x'
    - run: yarn install
    - run: yarn lint
    - run: yarn test
    - run: yarn test:functional
      env:
        CI: true

  build-windows:
    runs-on: windows-2019
    steps:
    - uses: zendesk/checkout@v2
    - name: Use Node.js
      uses: zendesk/setup-node@v1
      with:
        node-version: '12.x'
    - run: yarn install
    - run: yarn lint
    - run: yarn test
    - run: yarn test:functional
      env:
        CI: true
